name: Terraform Apply on Comment

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  apply-on-comment:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'terraform apply')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate OIDC token
        id: generate_token
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken();
            core.setOutput('id_token', id_token);

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::847025106884:role/githuboidc
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
