name: Terraform Plan on Comment

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  plan-on-comment:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'terraform plan')
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR context
        run: |
          echo "PR number: ${{ github.event.issue.number }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate OIDC token
        id: generate_token
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken();
            core.setOutput('id_token', id_token);

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::847025106884:role/githuboidc
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan | tee plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Post plan output as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: plan.txt
