permissions:
  id-token: write
  contents: read
name: Terraform Plan & Apply

on:
  pull_request:
    branches:
      - '**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3



      - name: Generate OIDC token
        id: generate_token
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken();
            core.setOutput('id_token', id_token);

      - name: Print OIDC token claims
        run: |
          echo "${{ steps.generate_token.outputs.id_token }}" | \
            awk -F. '{print $2}' | \
            base64 -d | jq .
        shell: bash
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::847025106884:role/githuboidc
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: production
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Generate OIDC token
        id: generate_token
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken();
            core.setOutput('id_token', id_token);

      - name: Print OIDC token claims
        run: |
          echo "${{ steps.generate_token.outputs.id_token }}" | base64 -d | jq .
        shell: bash
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::847025106884:role/githuboidc
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve